version: '3'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: postgres:11.6

  web-http:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: gunicorn -b 0.0.0.0:8000 --workers=4 djangoproject.wsgi:application
    volumes:
      - ./:/code
    expose:
      - 8000
    depends_on:
      - postgres

  web-sockets:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: daphne -b 0.0.0.0 -p 8001 djangoproject.asgi:application
    volumes:
      - ./:/code
    expose:
      - 8001
    depends_on:
      - postgres

